connection grexxconnect
address HOST_REPLACE_TOKEN:8883
topic COMMUNITY_TOPIC_REPLACE_TOKEN in 1
cleansession false
start_type automatic

remote_username USERNAME_REPLACE_TOKEN
remote_password PASSWORD_REPLACE_TOKEN

clientid CLIENT_ID_REPLACE_TOKEN

bridge_cafile /config/ssl/grexxconnect_ca.crt
log_type all

allow_anonymous true

listener 1885 0.0.0.0